#!/usr/bin/env ruby
#
# Command line utility for geocoding an address via Google's geocoding service.
#
require 'net/http'
require 'rexml/document'

query = ARGV[0].gsub(' ', '+')

base = "http://maps.google.com/maps/api/geocode/xml"
url  = URI.parse("#{base}?sensor=false&address=#{query}")
data = Net::HTTP.get_response(url).body
doc  = REXML::Document.new(data)

# make sure search found a result
e = doc.elements['GeocodeResponse/status']
(puts "not found"; exit) unless (e and e.text == "OK")

# isolate the relevant part of the result
place = doc.elements['GeocodeResponse/result/geometry/location']

# blindly use the first results (assume they are most accurate)
puts ['lat', 'lng'].map{ |i| place.elements[i].text.to_f }.join(',')

